In [60]:
import numpy as np

In [61]:
a=np.array((1,2,3,4.))

In [62]:
a.dtype

dtype('float64')

In [63]:
a

array([1., 2., 3., 4.])

In [64]:
a+1

array([2., 3., 4., 5.])

In [65]:
a

array([1., 2., 3., 4.])

In [66]:
a=np.array([[1.0,2,3],[4,5,6]])

In [67]:
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [68]:
b=np.array([10, 100, 1000])

In [69]:
b

array([  10,  100, 1000])

In [70]:
a[1, 1:2]

array([5.])

In [71]:
np.sum(a)

21.0

In [72]:
a.sum(axis=0)

array([5., 7., 9.])

In [73]:
np.arange(2*5).reshape(2,5, 1)

array([[[0],
        [1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8],
        [9]]])

In [74]:
print(np.eye.__doc__)


    Return a 2-D array with ones on the diagonal and zeros elsewhere.

    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.

        .. versionadded:: 1.14.0
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array objec

In [75]:
np.array([1, "test"])

array(['1', 'test'], dtype='<U21')

In [76]:
np.array([1, "test"])[1:]

array(['test'], dtype='<U21')

In [77]:
c=np.array([1,"test"])
c

array(['1', 'test'], dtype='<U21')