In [18]:
import numpy as np

In [19]:
a=np.array((1,2,3,4.))

In [20]:
a.dtype

dtype('float64')

In [21]:
a

array([1., 2., 3., 4.])

In [22]:
a+1

array([2., 3., 4., 5.])

In [23]:
a

array([1., 2., 3., 4.])

In [24]:
a=np.array([[1.0,2,3],[4,5,6]])

In [25]:
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [26]:
b=np.array([10, 100, 1000])

In [27]:
b

array([  10,  100, 1000])

In [28]:
a[1, 1:2]

array([5.])

In [29]:
np.sum(a)

21.0

In [30]:
a.sum(axis=0)

array([5., 7., 9.])

In [31]:
np.arange(2*5).reshape(2,5, 1)

array([[[0],
        [1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8],
        [9]]])

In [32]:
import pandas as pd

In [33]:
pd.read_excel("课程参与者.xlsx").info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   用户id    4 non-null      int64  
 1   姓名      4 non-null      object 
 2   年龄      4 non-null      int64  
 3   国家      4 non-null      object 
 4   分数      4 non-null      float64
 5   大陆      4 non-null      object 
dtypes: float64(1), int64(2), object(3)
memory usage: 320.0+ bytes


In [34]:
data = [["马克", 55, "意大利", 4.5, "欧洲"],
                ["约翰", 33, "美国", 6.7, "美洲"],
                ["提姆", 41, "美国", 3.9, "美洲"],
                ["珍妮", 12, "德国", 9.0, "欧洲"]]
df = pd.DataFrame(data=data,     
                          columns=["姓名", "年龄", "国家", "分数", "大陆"],
                          index=[1001, 1000, 1002, 1003])
df 

姓名  年龄   国家   分数  大陆
1001  马克  55  意大利  4.5  欧洲
1000  约翰  33   美国  6.7  美洲
1002  提姆  41   美国  3.9  美洲
1003  珍妮  12   德国  9.0  欧洲

In [41]:
df.loc[:, "姓名"]

用户ID
1001    马克
1000    约翰
1002    提姆
1003    珍妮
Name: 姓名, dtype: object

In [40]:
df.index.name="用户ID"

In [45]:
df

姓名  年龄   国家   分数  大陆
用户ID                      
1001  马克  55  意大利  4.5  欧洲
1000  约翰  33   美国  6.7  美洲
1002  提姆  41   美国  3.9  美洲
1003  珍妮  12   德国  9.0  欧洲

In [56]:
a = (df["年龄"] > 33) & (df["国家"] != "美国")
a

用户ID
1001     True
1000    False
1002    False
1003    False
dtype: bool

In [62]:
df.loc[a, :]

Index(['姓名', '年龄', '国家', '分数', '大陆'], dtype='object')

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__init__',
 '__init_subclass__',
 '__inv__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_arith_method',
 '_assert_can_do_setop',

In [48]:
df.columns.name="列名->"
df.index.name="用户ID"
df

列名->  姓名  年龄   国家   分数  大陆
用户ID                      
1001  马克  55  意大利  4.5  欧洲
1000  约翰  33   美国  6.7  美洲
1002  提姆  41   美国  3.9  美洲
1003  珍妮  12   德国  9.0  欧洲

In [52]:
df.reset_index().[1001, "姓名"]="a"

SyntaxError: invalid syntax (<ipython-input-52-493faab53ec2>, line 1)

In [53]:
df.T

用户ID 1001 1000 1002 1003
列名->                    
姓名     马克   约翰   提姆   珍妮
年龄     55   33   41   12
国家    意大利   美国   美国   德国
分数    4.5  6.7  3.9  9.0
大陆     欧洲   美洲   美洲   欧洲

In [54]:
df.T()

TypeError: 'DataFrame' object is not callable

In [57]:
help(df.reindex)


Help on method reindex in module pandas.core.frame:

reindex(labels=None, index=None, columns=None, axis=None, method=None, copy=True, level=None, fill_value=nan, limit=None, tolerance=None) method of pandas.core.frame.DataFrame instance
    Conform Series/DataFrame to new index with optional filling logic.
    
    Places NA/NaN in locations having no value in the previous index. A new object
    is produced unless the new index is equivalent to the current one and
    ``copy=False``.
    
    Parameters
    ----------
    
    keywords for axes : array-like, optional
        New labels / index to conform to, should be specified using
        keywords. Preferably an Index object to avoid duplicating data.
    
    method : {None, 'backfill'/'bfill', 'pad'/'ffill', 'nearest'}
        Method to use for filling holes in reindexed DataFrame.
        Please note: this is only applicable to DataFrames/Series with a
        monotonically increasing/decreasing index.
    
        * None (defa

In [58]:
help(df.loc)

Help on _LocIndexer in module pandas.core.indexing object:

class _LocIndexer(_LocationIndexer)
 |  Access a group of rows and columns by label(s) or a boolean array.
 |  
 |  ``.loc[]`` is primarily label based, but may also be used with a
 |  boolean array.
 |  
 |  Allowed inputs are:
 |  
 |  - A single label, e.g. ``5`` or ``'a'``, (note that ``5`` is
 |    interpreted as a *label* of the index, and **never** as an
 |    integer position along the index).
 |  - A list or array of labels, e.g. ``['a', 'b', 'c']``.
 |  - A slice object with labels, e.g. ``'a':'f'``.
 |  
 |    .. warning:: Note that contrary to usual python slices, **both** the
 |        start and the stop are included
 |  
 |  - A boolean array of the same length as the axis being sliced,
 |    e.g. ``[True, False, True]``.
 |  - An alignable boolean Series. The index of the key will be aligned before
 |    masking.
 |  - An alignable Index. The Index of the returned selection will be the input.
 |  - A ``callable`