In [2]:
import numpy as np

In [3]:
a=np.array((1,2,3,4.))

In [4]:
a.dtype

dtype('float64')

In [5]:
a

array([1., 2., 3., 4.])

In [6]:
a+1

array([2., 3., 4., 5.])

In [7]:
a

array([1., 2., 3., 4.])

In [17]:
a=np.array([[1.0,2,3],[4,5,6]])

In [18]:
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [19]:
b=np.array([10, 100, 1000])

In [20]:
b

array([  10,  100, 1000])

In [29]:
a[1, 1:2]

array([5.])

In [22]:
np.sum(a)

21.0

In [25]:
a.sum(axis=0)

array([5., 7., 9.])

In [31]:
np.arange(2*5).reshape(2,5, 1)

array([[[0],
        [1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8],
        [9]]])

In [34]:
print(np.random.randn.__doc__)


        randn(d0, d1, ..., dn)

        Return a sample (or samples) from the "standard normal" distribution.

        .. note::
            This is a convenience function for users porting code from Matlab,
            and wraps `standard_normal`. That function takes a
            tuple to specify the size of the output, which is consistent with
            other NumPy functions like `numpy.zeros` and `numpy.ones`.

        .. note::
            New code should use the ``standard_normal`` method of a ``default_rng()``
            instance instead; please see the :ref:`random-quick-start`.

        If positive int_like arguments are provided, `randn` generates an array
        of shape ``(d0, d1, ..., dn)``, filled
        with random floats sampled from a univariate "normal" (Gaussian)
        distribution of mean 0 and variance 1. A single float randomly sampled
        from the distribution is returned if no argument is provided.

        Parameters
        ----------
        d0, d