In [60]:
import numpy as np

In [61]:
a=np.array((1,2,3,4.))

In [62]:
a.dtype

dtype('float64')

In [63]:
a

array([1., 2., 3., 4.])

In [64]:
a+1

array([2., 3., 4., 5.])

In [65]:
a

array([1., 2., 3., 4.])

In [66]:
a=np.array([[1.0,2,3],[4,5,6]])

In [67]:
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [68]:
b=np.array([10, 100, 1000])

In [69]:
b

array([  10,  100, 1000])

In [70]:
a[1, 1:2]

array([5.])

In [71]:
np.sum(a)

21.0

In [72]:
a.sum(axis=0)

array([5., 7., 9.])

In [73]:
np.arange(2*5).reshape(2,5, 1)

array([[[0],
        [1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8],
        [9]]])

In [82]:
import pandas as pd

In [98]:
pd.read_excel("课程参与者.xlsx").info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   用户id    4 non-null      int64  
 1   姓名      4 non-null      object 
 2   年龄      4 non-null      int64  
 3   国家      4 non-null      object 
 4   分数      4 non-null      float64
 5   大陆      4 non-null      object 
dtypes: float64(1), int64(2), object(3)
memory usage: 320.0+ bytes


In [96]:
data = [["马克", 55, "意大利", 4.5, "欧洲"],
                ["约翰", 33, "美国", 6.7, "美洲"],
                ["提姆", 41, "美国", 3.9, "美洲"],
                ["珍妮", 12, "德国", 9.0, "欧洲"]]
df = pd.DataFrame(data=data,     
                          columns=["姓名", "年龄", "国家", "分数", "大陆"],
                          index=[1001, 1000, 1002, 1003])
df 

姓名  年龄   国家   分数  大陆
1001  马克  55  意大利  4.5  欧洲
1000  约翰  33   美国  6.7  美洲
1002  提姆  41   美国  3.9  美洲
1003  珍妮  12   德国  9.0  欧洲

In [99]:
data = [["马克", 55, "意大利", 4.5, "欧洲"],
                ["约翰", 33, "美国", 6.7, "美洲"],
                ["提姆", 41, "美国", 3.9, "美洲"],
                ["珍妮", 12, "德国", 9.0, "欧洲"]]
df = pd.DataFrame(data=data,     
                          columns=["姓名", "年龄", "国家", "分数", "大陆"])
df 

姓名  年龄   国家   分数  大陆
0  马克  55  意大利  4.5  欧洲
1  约翰  33   美国  6.7  美洲
2  提姆  41   美国  3.9  美洲
3  珍妮  12   德国  9.0  欧洲