In [13]:
import numpy as np

In [18]:
a=np.array((1,2,3,4.))

In [19]:
a.dtype

dtype('float64')

In [20]:
a

array([1., 2., 3., 4.])

In [21]:
a+1

array([2., 3., 4., 5.])

In [22]:
a

array([1., 2., 3., 4.])

In [23]:
a=np.array([[1,2,3],[4,5,6]])

In [24]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
b=np.array([10, 100, 1000])

In [26]:
b

array([ 10, 100])

In [29]:
b*a

array([[  10,  200, 3000],
       [  40,  500, 6000]])