In [2]:
import numpy as np

In [3]:
a=np.array((1,2,3,4.))

In [4]:
a.dtype

dtype('float64')

In [5]:
a

array([1., 2., 3., 4.])

In [6]:
a+1

array([2., 3., 4., 5.])

In [7]:
a

array([1., 2., 3., 4.])

In [17]:
a=np.array([[1.0,2,3],[4,5,6]])

In [18]:
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [19]:
b=np.array([10, 100, 1000])

In [20]:
b

array([  10,  100, 1000])

In [21]:
b*a

array([[  10.,  200., 3000.],
       [  40.,  500., 6000.]])

In [22]:
np.sum(a)

21.0

In [23]:
a.sum()

21.0

In [24]:
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [25]:
a.sum(axis=0)

array([5., 7., 9.])