In [18]:
import numpy as np

In [19]:
a=np.array((1,2,3,4.))

In [20]:
a.dtype

dtype('float64')

In [21]:
a

array([1., 2., 3., 4.])

In [22]:
a+1

array([2., 3., 4., 5.])

In [23]:
a

array([1., 2., 3., 4.])

In [24]:
a=np.array([[1.0,2,3],[4,5,6]])

In [25]:
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [26]:
b=np.array([10, 100, 1000])

In [27]:
b

array([  10,  100, 1000])

In [28]:
a[1, 1:2]

array([5.])

In [29]:
np.sum(a)

21.0

In [30]:
a.sum(axis=0)

array([5., 7., 9.])

In [31]:
np.arange(2*5).reshape(2,5, 1)

array([[[0],
        [1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8],
        [9]]])

In [32]:
import pandas as pd

In [33]:
pd.read_excel("课程参与者.xlsx").info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   用户id    4 non-null      int64  
 1   姓名      4 non-null      object 
 2   年龄      4 non-null      int64  
 3   国家      4 non-null      object 
 4   分数      4 non-null      float64
 5   大陆      4 non-null      object 
dtypes: float64(1), int64(2), object(3)
memory usage: 320.0+ bytes


In [34]:
data = [["马克", 55, "意大利", 4.5, "欧洲"],
                ["约翰", 33, "美国", 6.7, "美洲"],
                ["提姆", 41, "美国", 3.9, "美洲"],
                ["珍妮", 12, "德国", 9.0, "欧洲"]]
df = pd.DataFrame(data=data,     
                          columns=["姓名", "年龄", "国家", "分数", "大陆"],
                          index=[1001, 1000, 1002, 1003])
df 

姓名  年龄   国家   分数  大陆
1001  马克  55  意大利  4.5  欧洲
1000  约翰  33   美国  6.7  美洲
1002  提姆  41   美国  3.9  美洲
1003  珍妮  12   德国  9.0  欧洲

In [41]:
df.loc[:, "姓名"]

用户ID
1001    马克
1000    约翰
1002    提姆
1003    珍妮
Name: 姓名, dtype: object

In [40]:
df.index.name="用户ID"

In [45]:
df

姓名  年龄   国家   分数  大陆
用户ID                      
1001  马克  55  意大利  4.5  欧洲
1000  约翰  33   美国  6.7  美洲
1002  提姆  41   美国  3.9  美洲
1003  珍妮  12   德国  9.0  欧洲

In [56]:
a = (df["年龄"] > 33) & (df["国家"] != "美国")
a

用户ID
1001     True
1000    False
1002    False
1003    False
dtype: bool

In [62]:
df.loc[a, :]

Index(['姓名', '年龄', '国家', '分数', '大陆'], dtype='object')

In [83]:
data = np.array({
                "城市1": [300.1, 100.2],
                "城市2": [400.3, 300.4],
                "城市3": [1000.5, 1100.6]})
[print(1) for row in data]

TypeError: iteration over a 0-d array

In [65]:
df.columns.name="列名->"
df.index.name="用户ID"
df

列名->  姓名  年龄   国家   分数  大陆
用户ID                      
1001  马克  55  意大利  4.5  欧洲
1000  约翰  33   美国  6.7  美洲
1002  提姆  41   美国  3.9  美洲
1003  珍妮  12   德国  9.0  欧洲

In [66]:
df.reset_index().[1001, "姓名"]="a"

SyntaxError: invalid syntax (<ipython-input-66-493faab53ec2>, line 1)

In [ ]:
df.T

In [ ]:
df.T()

In [ ]:
help(df.reindex)


In [ ]:
help(df.loc)